# floor_id = 0 → negro (sin tile)

#  Piedra ----------------------------------
[floor.1]
path = "assets/tiles/floor/piedra.png"

#  Pasto ----------------------------------
[floor.2]
path = "assets/tiles/floor/pasto_1.png"
tile_size = 2

[floor.3]
path = "assets/tiles/floor/pasto_2.png"
tile_size = 2

[floor.4]
path = "assets/tiles/floor/pasto_3.png"
tile_size = 2

[floor.5]
path = "assets/tiles/floor/pasto_4.png"
tile_size = 2

[floor.6]
path = "assets/tiles/floor/pasto_5.png"
tile_size = 2

[floor.7]
path = "assets/tiles/floor/pasto_6.png"
tile_size = 2

[floor.8]
path = "assets/tiles/floor/pasto_7.png"
tile_size = 2

#  Tierra (pueblo) -------------------------
[floor.10]
path = "assets/tiles/floor/tierra_1.png"

[floor.11]
path = "assets/tiles/floor/tierra_2.png"

[floor.12]
path = "assets/tiles/floor/tierra_3.png"

[floor.13]
path = "assets/tiles/floor/tierra_4.png"

#  Franja tierra-pasto ----------------------------------
[floor.40]
path = "assets/tiles/floor/arena_franja_pasto.png"
tile_size = 2

[floor.41]
path = "assets/tiles/floor/arena_franja_pasto.png"
tile_size = 2

[floor.42]
path = "assets/tiles/floor/arena_franja_pasto.png"
tile_size = 2

[floor.43]
path = "assets/tiles/floor/arena_franja_pasto.png"
tile_size = 2

#  Agua ------------------------------------------------
[floor.44]
path = "assets/tiles/floor/agua.png"
tile_size = 2

#  Arena -----------------------------------------------
[floor.45]
path = "assets/tiles/floor/arena.png"
tile_size = 2

[floor.46]
path = "assets/tiles/floor/arena_franja_pasto.png"
tile_size = 2

#  Acantilado ------------------------------------------
[floor.50]
path = "assets/tiles/floor/acantilado_norte_1.png"
tile_size = 6
offset_y = -42

[floor.51]
path = "assets/tiles/floor/acantilado_sur_1.png"
tile_size = 6
offset_y = 0

[floor.52]
path = "assets/tiles/floor/acantilado_oeste_1.png"
tile_size = 6
offset_x = -384
offset_y = -64

[floor.53]
path = "assets/tiles/floor/acantilado_esquina_nw.png"
tile_size = 6
offset_x = -384
offset_y = -108

[floor.54]
path = "assets/tiles/floor/acantilado_esquina_ne.png"
tile_size = 6
offset_y = -42

[floor.55]
path = "assets/tiles/floor/acantilado_esquina_sw.png"
tile_size = 6
offset_x = -384
offset_y = 64

[floor.56]
path = "assets/tiles/floor/acantilado_esquina_se.png"
tile_size = 6
offset_x = 0
offset_y = 0

# Caminos ----------------------------------------------------
[floor.60]
path = "assets/tiles/floor/camino_vertical_1.png"
tile_size = 2

[floor.61]
path = "assets/tiles/floor/camino_vertical_2.png"
tile_size = 2

[floor.62]
path = "assets/tiles/floor/camino_vertical_3.png"
tile_size = 2

[floor.63]
path = "assets/tiles/floor/camino_vertical_4.png"
tile_size = 2

[floor.64]
path = "assets/tiles/floor/camino_horizontal_1.png"
tile_size = 2

[floor.65]
path = "assets/tiles/floor/camino_horizontal_2.png"
tile_size = 2

[floor.66]
path = "assets/tiles/floor/camino_horizontal_3.png"
tile_size = 2

[floor.67]
path = "assets/tiles/floor/camino_horizontal_4.png"
tile_size = 2

# Terminaciones / esquineros de camino -----------------------------------
[floor.68]
path = "assets/tiles/floor/camino_norte.png"

[floor.69]
path = "assets/tiles/floor/camino_sur.png"

[floor.70]
path = "assets/tiles/floor/camino_este.png"

[floor.71]
path = "assets/tiles/floor/camino_oeste.png"

[floor.72]
path = "assets/tiles/floor/camino_interseccion.png"
tile_size = 2